#import "../../../fragments/TaskFields.graphql"
#import "../../../fragments/ReminderFields.graphql"
#import "../../../fragments/MemoryFields.graphql"

mutation SubmitCapture($rawInput: String!) {
  submitCapture(rawInput: $rawInput) {
    __typename
    ... on TaskCreated {
      task {
        ...TaskFields
      }
    }
    ... on TasksListed {
      tasks {
        ...TaskFields
      }
    }
    ... on ReminderCreated {
      reminder {
        ...ReminderFields
      }
    }
    ... on RemindersListed {
      reminders {
        ...ReminderFields
      }
    }
    ... on ReminderLimitReached {
      message
      limit
    }
    ... on MemorySaved {
      memory {
        ...MemoryFields
      }
      secretCaution
    }
    ... on MemoriesListed {
      memories {
        ...MemoryFields
      }
      searchText
    }
    ... on MemoryTooLong {
      message
      length
      limit
    }
    ... on ForgetCandidates {
      forgetText: searchText
      totalMatches
      forgetAll
      allCount
      candidates {
        ...MemoryFields
      }
    }
    ... on PendingQuestionCreated {
      pendingCaptureId
      question
    }
    ... on NonCommandGuidance {
      originalInput
    }
    ... on UnrecognisedCommand {
      attemptedName
      closestMatches
    }
    ... on UserLimitReached {
      message
      limit
      resetsAt
    }
    ... on ProviderUnavailable {
      message
    }
    ... on ProviderTimeout {
      message
      budgetSeconds
    }
    ... on SharedQuotaExhausted {
      message
    }
    ... on MalformedResult {
      message
      reason
    }
  }
}
